name: Python package

on:
  schedule:
    - cron:  '20 16,20,23 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.1'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Pip list
        run: pip list
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
