name: Python package

on:
  workflow_dispatch:
  schedule:
    - cron:  '20 16,20,23 * * 1-5'

env:
  JIRA_USR: ${{ secrets.CI_JIRA_USR }}
  JIRA_API_TKN: ${{ secrets.CI_JIRA_API_TKN }}
  

jobs:
  script-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.1'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Running script
        run: python hello-world.py
